version: '3.0'

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

services:
  pihole:
    container_name: pihole
    image: heyhiren/pihole-unbound:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_WEBPORT:-8180}:8180/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
    dns:
      - 127.0.0.1
    environment:
      WEB_PORT: "8180"
      TZ: "${TZ:-UTC}"
      WEBPASSWORD: "${WEBPASSWORD}"
      FTLCONF_LOCAL_IPV4: "${FTLCONF_LOCAL_IPV4}"
      PIHOLE_DNS_: "127.0.0.1#5335"
      REV_SERVER: "${REV_SERVER:-false}"
      REV_SERVER_TARGET: "${REV_SERVER_TARGET}"
      REV_SERVER_DOMAIN: "${REV_SERVER_DOMAIN}"
      REV_SERVER_CIDR: "${REV_SERVER_CIDR}"
      DNSSEC: "true"
      DNSMASQ_LISTENING: "single"
    volumes:
      - ~/.pihole-unbound/etc-pihole/:/etc/pihole:rw
      - ~/.pihole-unbound/etc-dnsmasq/:/etc/dnsmasq.d:rw
    restart: unless-stopped
    
    # Uncomment the below to disable logging in docker.
    # logging:
    #   driver: "none"